//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @BedMenu
        {
            private const string NAME = "BedMenu";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @teleport_to_hub => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 54089379840);
			public static long @teleport_to_hub_key = 54089379840;
			public static string @return_back => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 232955473920);
			public static long @return_back_key = 232955473920;
			public static string @restart_level => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 41958979143364608);
			public static long @restart_level_key = 41958979143364608;

        }
    }
}
