//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Dialog_GateSilentCreek
        {
            private const string NAME = "Dialog_GateSilentCreek";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @start_message => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 21740589200076800);
			public static long @start_message_key = 21740589200076800;
			public static string @near_scarecrow => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 21746756999606272);
			public static long @near_scarecrow_key = 21746756999606272;
			public static string @near_scarecrow_end => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 21747300573016064);
			public static long @near_scarecrow_end_key = 21747300573016064;
			public static string @location_end => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 21747975600107520);
			public static long @location_end_key = 21747975600107520;
			public static string @New_Entry => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 25125881634254848);
			public static long @New_Entry_key = 25125881634254848;

        }
    }
}
