//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Dialog_3_IN_1
        {
            private const string NAME = "Dialog_3_IN_1";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @devil_story => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 69868351488);
			public static long @devil_story_key = 69868351488;
			public static string @boss_meet => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 500364746584064);
			public static long @boss_meet_key = 500364746584064;

        }
    }
}
