//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Dialog_2_IN_1
        {
            private const string NAME = "Dialog_2_IN_1";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @start_message => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 145030279168);
			public static long @start_message_key = 145030279168;
			public static string @try_go_back => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1485265596416);
			public static long @try_go_back_key = 1485265596416;

        }
    }
}
