//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Dialog_4_IN_1
        {
            private const string NAME = "Dialog_4_IN_1";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @boss_meet => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 439037042782208);
			public static long @boss_meet_key = 439037042782208;
			public static string @final_dialog => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 160494678016);
			public static long @final_dialog_key = 160494678016;

        }
    }
}
