//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Dialog_0_IN_1
        {
            private const string NAME = "Dialog_0_IN_1";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @start_message => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 8634307576492032);
			public static long @start_message_key = 8634307576492032;
			public static string @level_1_first_meet => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 10949132314898432);
			public static long @level_1_first_meet_key = 10949132314898432;
			public static string @level_1_boss_meet => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 11349092818644992);
			public static long @level_1_boss_meet_key = 11349092818644992;
			public static string @level_1_boss_we_win => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 11545512381149184);
			public static long @level_1_boss_we_win_key = 11545512381149184;

        }
    }
}
