//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Dialog_Titles
        {
            private const string NAME = "Dialog_Titles";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @lachesis => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 49614057472);
			public static long @lachesis_key = 49614057472;
			public static string @devil => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 12813349964312576);
			public static long @devil_key = 12813349964312576;
			public static string @asterion => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 23945326909616128);
			public static long @asterion_key = 23945326909616128;
			public static string @lilit => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 23945342403375104);
			public static long @lilit_key = 23945342403375104;
			public static string @cain => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 23953582239412224);
			public static long @cain_key = 23953582239412224;
			public static string @cockroach => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 24387568723980288);
			public static long @cockroach_key = 24387568723980288;

        }
    }
}
