//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @EnhancementDescriptions
        {
            private const string NAME = "EnhancementDescriptions";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @damage => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 148964536320);
			public static long @damage_key = 148964536320;
			public static string @damage_percent => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58377334863589376);
			public static long @damage_percent_key = 58377334863589376;
			public static string @hp => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58377344653094912);
			public static long @hp_key = 58377344653094912;
			public static string @hp_percent => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58377489599852544);
			public static long @hp_percent_key = 58377489599852544;
			public static string @crit_chanсe => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58377561930625024);
			public static long @crit_chanсe_key = 58377561930625024;
			public static string @crit_damage => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58377626413854720);
			public static long @crit_damage_key = 58377626413854720;
			public static string @defence => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 60902605701410816);
			public static long @defence_key = 60902605701410816;
			public static string @shock_wave => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 65537046251991040);
			public static long @shock_wave_key = 65537046251991040;
			public static string @damage_orb => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 65669099794624512);
			public static long @damage_orb_key = 65669099794624512;
			public static string @through_projectile => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 60841149727404032);
			public static long @through_projectile_key = 60841149727404032;

        }
    }
}
