//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @EnhancementNames
        {
            private const string NAME = "EnhancementNames";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @damage => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 119537758208);
			public static long @damage_key = 119537758208;
			public static string @damage_percent => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58766545483624448);
			public static long @damage_percent_key = 58766545483624448;
			public static string @hp => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58766554006450176);
			public static long @hp_key = 58766554006450176;
			public static string @hp_percent => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58769135684448256);
			public static long @hp_percent_key = 58769135684448256;
			public static string @crit_chanсe => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58769145385873408);
			public static long @crit_chanсe_key = 58769145385873408;
			public static string @crit_damage => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58769193347739648);
			public static long @crit_damage_key = 58769193347739648;
			public static string @defence => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 61308896743682048);
			public static long @defence_key = 61308896743682048;
			public static string @shock_wave => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 65941449593221120);
			public static long @shock_wave_key = 65941449593221120;
			public static string @damage_orb => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 66073401205878784);
			public static long @damage_orb_key = 66073401205878784;
			public static string @through_projectile => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 61244621522104320);
			public static long @through_projectile_key = 61244621522104320;

        }
    }
}
