//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @FinalTitles
        {
            private const string NAME = "FinalTitles";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @message => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 33184968704);
			public static long @message_key = 33184968704;
			public static string @submit => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 43081881251840);
			public static long @submit_key = 43081881251840;

        }
    }
}
