//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @GameMenuHeadTitles
        {
            private const string NAME = "GameMenuHeadTitles";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @chips => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 63367180288);
			public static long @chips_key = 63367180288;
			public static string @skills => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 70522662912);
			public static long @skills_key = 70522662912;
			public static string @equipment => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 74549194752);
			public static long @equipment_key = 74549194752;
			public static string @settings => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 77778808832);
			public static long @settings_key = 77778808832;

        }
    }
}
