//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @InputTooltip
        {
            private const string NAME = "InputTooltip";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @pick => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 8573251584);
			public static long @pick_key = 8573251584;
			public static string @hold_to_break_crystals => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1932697628672);
			public static long @hold_to_break_crystals_key = 1932697628672;
			public static string @wardrobe => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 2026163499008);
			public static long @wardrobe_key = 2026163499008;
			public static string @teleport => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 28275388450500608);
			public static long @teleport_key = 28275388450500608;
			public static string @chest => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 28291878889353216);
			public static long @chest_key = 28291878889353216;
			public static string @bed => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 28292077116354560);
			public static long @bed_key = 28292077116354560;

        }
    }
}
