//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Inventory
        {
            private const string NAME = "Inventory";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @close_inventory => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 298789269504);
			public static long @close_inventory_key = 298789269504;
			public static string @insert_enhancement => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 969729929539584);
			public static long @insert_enhancement_key = 969729929539584;
			public static string @remove_enhancement => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 970219207684096);
			public static long @remove_enhancement_key = 970219207684096;
			public static string @pop_confirm_message => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 37179831095029760);
			public static long @pop_confirm_message_key = 37179831095029760;
			public static string @destroy_to_gem => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 37198824585457664);
			public static long @destroy_to_gem_key = 37198824585457664;
			public static string @previous_tab => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 41533883966713856);
			public static long @previous_tab_key = 41533883966713856;
			public static string @next_tab => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 41534084697714688);
			public static long @next_tab_key = 41534084697714688;

        }
    }
}
