//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @InventoryPlayerStatesVT
        {
            private const string NAME = "InventoryPlayerStatesVT";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @atk => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 47386882048);
			public static long @atk_key = 47386882048;
			public static string @def => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 184645480448);
			public static long @def_key = 184645480448;
			public static string @crch => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 233731420160);
			public static long @crch_key = 233731420160;
			public static string @crd => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 793759084544);
			public static long @crd_key = 793759084544;
			public static string @energy_used => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 37040346122317824);
			public static long @energy_used_key = 37040346122317824;
			public static string @status => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 37694461894619136);
			public static long @status_key = 37694461894619136;
			public static string @hp => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 38038067964702720);
			public static long @hp_key = 38038067964702720;
			public static string @mp => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 38038147023138816);
			public static long @mp_key = 38038147023138816;

        }
    }
}
