//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @ItemContextMenuVT
        {
            private const string NAME = "ItemContextMenuVT";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @destroy_to_gem => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 197622657024);
			public static long @destroy_to_gem_key = 197622657024;
			public static string @drop => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 201137483776);
			public static long @drop_key = 201137483776;
			public static string @submit => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 111316458696704);
			public static long @submit_key = 111316458696704;
			public static string @cancel => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 111425833562112);
			public static long @cancel_key = 111425833562112;

        }
    }
}
