//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @MagicGemMenuVT
        {
            private const string NAME = "MagicGemMenuVT";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @attack_gem_title => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 7684929253376);
			public static long @attack_gem_title_key = 7684929253376;
			public static string @defence_gem_title => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 7879687565312);
			public static long @defence_gem_title_key = 7879687565312;
			public static string @hitpoint_gem_title => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58238342688768);
			public static long @hitpoint_gem_title_key = 58238342688768;
			public static string @attack_gem_description => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 8026819555328);
			public static long @attack_gem_description_key = 8026819555328;
			public static string @defence_gem_description => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 9035742605312);
			public static long @defence_gem_description_key = 9035742605312;
			public static string @hitpoint_gem_description => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58415992434688);
			public static long @hitpoint_gem_description_key = 58415992434688;
			public static string @submit => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 9868832043008);
			public static long @submit_key = 9868832043008;

        }
    }
}
