//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @MainMenuVT
        {
            private const string NAME = "MainMenuVT";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @new_game => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 18748174336);
			public static long @new_game_key = 18748174336;
			public static string @settings => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 7716617220096);
			public static long @settings_key = 7716617220096;
			public static string @settings_close => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 523431652782080);
			public static long @settings_close_key = 523431652782080;
			public static string @submit => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 20671590907408384);
			public static long @submit_key = 20671590907408384;
			public static string @up => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 20729196652949504);
			public static long @up_key = 20729196652949504;
			public static string @down => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 20729438114836480);
			public static long @down_key = 20729438114836480;
			public static string @continue_game => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 25381305746878464);
			public static long @continue_game_key = 25381305746878464;
			public static string @remove => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 50098875942989824);
			public static long @remove_key = 50098875942989824;

        }
    }
}
