//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @PlayerAbilitiesVT_titles
        {
            private const string NAME = "PlayerAbilitiesVT_titles";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @double_jump => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 392628293758976);
			public static long @double_jump_key = 392628293758976;
			public static string @triple_jump => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 392912113922048);
			public static long @triple_jump_key = 392912113922048;
			public static string @energy_level => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 48270870945886208);
			public static long @energy_level_key = 48270870945886208;
			public static string @mana_level => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 48271066920546304);
			public static long @mana_level_key = 48271066920546304;
			public static string @dash_recovery_speed => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 57244777363173376);
			public static long @dash_recovery_speed_key = 57244777363173376;
			public static string @healing_potion => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 57247012046401536);
			public static long @healing_potion_key = 57247012046401536;

        }
    }
}
