//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @PlayerAbilitiesVT_navigation
        {
            private const string NAME = "PlayerAbilitiesVT_navigation";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @move => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 12758708224);
			public static long @move_key = 12758708224;
			public static string @submit => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 135848947712);
			public static long @submit_key = 135848947712;
			public static string @cancel => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1217287319552);
			public static long @cancel_key = 1217287319552;

        }
    }
}
