//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @PlayerAbilitiesVT_descriptions
        {
            private const string NAME = "PlayerAbilitiesVT_descriptions";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @double_jump => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 4409295269888);
			public static long @double_jump_key = 4409295269888;
			public static string @triple_jump => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 4524315668480);
			public static long @triple_jump_key = 4524315668480;
			public static string @dash_recovery_speed => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 56772014601039872);
			public static long @dash_recovery_speed_key = 56772014601039872;
			public static string @healing_potion => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 56772589174550528);
			public static long @healing_potion_key = 56772589174550528;
			public static string @mana_level => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 56773248309424128);
			public static long @mana_level_key = 56773248309424128;
			public static string @energy_level => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 56773580267614208);
			public static long @energy_level_key = 56773580267614208;

        }
    }
}
