//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @SettingsVT
        {
            private const string NAME = "SettingsVT";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @master_volume => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 9946221146112);
			public static long @master_volume_key = 9946221146112;
			public static string @language_value => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 14951741288448);
			public static long @language_value_key = 14951741288448;
			public static string @language_label => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 30415527768064);
			public static long @language_label_key = 30415527768064;
			public static string @shadows => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 13755838199656448);
			public static long @shadows_key = 13755838199656448;
			public static string @up => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40208228926779392);
			public static long @up_key = 40208228926779392;
			public static string @down => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40208297235214336);
			public static long @down_key = 40208297235214336;
			public static string @change => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40208342487560192);
			public static long @change_key = 40208342487560192;
			public static string @close => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40208429355790336);
			public static long @close_key = 40208429355790336;
			public static string @background_volume => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40527165954617344);
			public static long @background_volume_key = 40527165954617344;
			public static string @sfx_volume => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40527335593242624);
			public static long @sfx_volume_key = 40527335593242624;
			public static string @drawing_distance => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 54999192136478720);
			public static long @drawing_distance_key = 54999192136478720;

        }
    }
}
