//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @SlotTagNames
        {
            private const string NAME = "SlotTagNames";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @ThroughProjectileSlot => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 12557381632);
			public static long @ThroughProjectileSlot_key = 12557381632;

        }
    }
}
