//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @TutorialShowWeaponTab
        {
            private const string NAME = "TutorialShowWeaponTab";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @open_menu => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 3845102661632);
			public static long @open_menu_key = 3845102661632;
			public static string @about_navigation => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 420134678528);
			public static long @about_navigation_key = 420134678528;
			public static string @about_header => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 409472757760);
			public static long @about_header_key = 409472757760;
			public static string @abaut_weapon => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 435607465984);
			public static long @abaut_weapon_key = 435607465984;

        }
    }
}
