//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @TutorialBuyDoubleJump
        {
            private const string NAME = "TutorialBuyDoubleJump";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @about_header => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1465669808128);
			public static long @about_header_key = 1465669808128;
			public static string @about_navigation => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 58917023744);
			public static long @about_navigation_key = 58917023744;
			public static string @press_right_trigger_1 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1738744164352);
			public static long @press_right_trigger_1_key = 1738744164352;
			public static string @press_right_trigger_2 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 3696875958272);
			public static long @press_right_trigger_2_key = 3696875958272;

        }
    }
}
