//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @Tutorials
        {
            private const string NAME = "Tutorials";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @combo_1 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 25270317056);
			public static long @combo_1_key = 25270317056;
			public static string @combo_2 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 51237164314624);
			public static long @combo_2_key = 51237164314624;
			public static string @combo_3 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 51242822430720);
			public static long @combo_3_key = 51242822430720;
			public static string @combo_4 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40729574345699328);
			public static long @combo_4_key = 40729574345699328;
			public static string @combo_5 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40729626128576512);
			public static long @combo_5_key = 40729626128576512;
			public static string @combo_6 => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 40729628578050048);
			public static long @combo_6_key = 40729628578050048;
			public static string @jump(List<object> o) => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1982669201764352);
			public static long @jump_key = 1982669201764352;
			public static string @collect_keys => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1992053386539008);
			public static long @collect_keys_key = 1992053386539008;
			public static string @dash(List<object> o) => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1993802906234880);
			public static long @dash_key = 1993802906234880;
			public static string @jump_down(List<object> o) => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1993809545818112);
			public static long @jump_down_key = 1993809545818112;
			public static string @break_Items(List<object> o) => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 2178779102998528);
			public static long @break_Items_key = 2178779102998528;
			public static string @move(List<object> o) => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 2188019582529536);
			public static long @move_key = 2188019582529536;
			public static string @choose_weapon => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 2188350706053120);
			public static long @choose_weapon_key = 2188350706053120;
			public static string @jump_crush_wall => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 44314325287596032);
			public static long @jump_crush_wall_key = 44314325287596032;

        }
    }
}
