//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @TutorialAboutSave
        {
            private const string NAME = "TutorialAboutSave";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @about_save => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 12548993024);
			public static long @about_save_key = 12548993024;
			public static string @about_restore => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1728945837469696);
			public static long @about_restore_key = 1728945837469696;

        }
    }
}
