//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @ValueEnumNames
        {
            private const string NAME = "ValueEnumNames";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @CriticalChanceValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 101581484032);
			public static long @CriticalChanceValue_key = 101581484032;
			public static string @CriticalDamageValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1124278628352);
			public static long @CriticalDamageValue_key = 1124278628352;
			public static string @DamageValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1550466052096);
			public static long @DamageValue_key = 1550466052096;
			public static string @DamagePercentValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1614626320384);
			public static long @DamagePercentValue_key = 1614626320384;
			public static string @DefenceValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1758054739968);
			public static long @DefenceValue_key = 1758054739968;
			public static string @HitPointValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1792510947328);
			public static long @HitPointValue_key = 1792510947328;
			public static string @HitPointMaxValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 9173633049718784);
			public static long @HitPointMaxValue_key = 9173633049718784;
			public static string @ManaPointValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 2012917428224);
			public static long @ManaPointValue_key = 2012917428224;
			public static string @ManaPointMaxValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 9173766948679680);
			public static long @ManaPointMaxValue_key = 9173766948679680;
			public static string @RecoverySpeedManaPointValue => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 2124737572864);
			public static long @RecoverySpeedManaPointValue_key = 2124737572864;

        }
    }
}
