//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @WeaponsTabVT
        {
            private const string NAME = "WeaponsTabVT";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @current_weapon => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 414958290104320);
			public static long @current_weapon_key = 414958290104320;
			public static string @selected_weapon => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 415053001682944);
			public static long @selected_weapon_key = 415053001682944;
			public static string @use => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 419715205459968);
			public static long @use_key = 419715205459968;
			public static string @destroy_to_gem => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 419835078668288);
			public static long @destroy_to_gem_key = 419835078668288;
			public static string @close_inventory => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 422609946308608);
			public static long @close_inventory_key = 422609946308608;

        }
    }
}
