//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @WeaponDescriptions
        {
            private const string NAME = "WeaponDescriptions";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @rapier => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 1557717847797760);
			public static long @rapier_key = 1557717847797760;
			public static string @paired_blades => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 52112398202073088);
			public static long @paired_blades_key = 52112398202073088;
			public static string @sword_and_shield => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 52112413045714944);
			public static long @sword_and_shield_key = 52112413045714944;
			public static string @katana => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 52112563398930432);
			public static long @katana_key = 52112563398930432;
			public static string @spear => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 52112577630203904);
			public static long @spear_key = 52112577630203904;

        }
    }
}
