//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
 
using System.Collections.Generic;
using UnityEngine.Localization.Settings;
using UnityEngine.Localization;
 
namespace LurkingNinja.MyGame.Internationalization
{
    public static partial class I18N
    {
        public static class @WeaponNames
        {
            private const string NAME = "WeaponNames";
            public static LocalizedStringTable Table = new LocalizedStringTable{ TableReference = NAME };
			public static string @rapier => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 50092666880);
			public static long @rapier_key = 50092666880;
			public static string @paired_blades => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 63225032704);
			public static long @paired_blades_key = 63225032704;
			public static string @sword_and_shield => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 67448696832);
			public static long @sword_and_shield_key = 67448696832;
			public static string @katana => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 70263074816);
			public static long @katana_key = 70263074816;
			public static string @spear => LocalizationSettings.StringDatabase.GetLocalizedString(NAME, 73538826240);
			public static long @spear_key = 73538826240;

        }
    }
}
